defaults:
  - _self_

name: improved_gcn

init:
  _target_: models.ImprovedGCN
  _partial_: false
  
  num_node_features: 11
  hidden_channels: 512
  num_layers: 6
  
  dropout: 0.1
  edge_dropout: 0.0
  
  normalization: graph
  num_groups: 8 
  
  activation: relu
  
  pooling: attention
  
  use_residual: false
  
  aggregation: add