defaults:
  - dataset: qm9
  - trainer: ncps-train
  - logger: wandb
  - model: dimenet
  - _self_


seed: 42 # Random seed
device: unset # Device to use (cuda or cpu) if unset will use cuda if available
force_deterministic: False # Force deterministic algorithms
debug_mode: False # Debug mode
result_dir: ./results
compile_model: false # Whether to compile the model with torch.compile
